import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  step: 1,
  dummyEmployeeData :  [
    {
      id: 1,
      name: "John Doe",
      position: "Software Engineer",
      department: "Engineering",
      email: "john.doe@example.com",
      experience: "5 years",
      status: "Active",
      officeAddress: "123 Main Street, City",
      subordinates: ["Alice", "Bob"],
      birthday: "January 15, 1985",
      contact: "+1 123-456-7890",
    },
    {
      id: 2,
      name: "Jane Smith",
      position: "Product Manager",
      department: "Product Management",
      email: "jane.smith@example.com",
      experience: "8 years",
      status: "Active",
      officeAddress: "456 Elm Street, City",
      subordinates: ["Ella", "Frank"],
      birthday: "March 20, 1980",
      contact: "+1 234-567-8901",
    },
    {
      id: 3,
      name: "Bob Johnson",
      position: "Marketing Specialist",
      department: "Marketing",
      email: "bob.johnson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "789 Oak Street, City",
      subordinates: ["Grace", "Henry"],
      birthday: "November 10, 1990",
      contact: "+1 345-678-9012",
    },
    {
      id: 4,
      name: "Alice Williams",
      position: "Data Analyst",
      department: "Analytics",
      email: "alice.williams@example.com",
      experience: "3 years",
      status: "Active",
      officeAddress: "101 Pine Street, City",
      subordinates: ["Jack", "Karen"],
      birthday: "May 5, 1995",
      contact: "+1 456-789-0123",
    },
    {
      id: 5,
      name: "Michael Brown",
      position: "HR Manager",
      department: "Human Resources",
      email: "michael.brown@example.com",
      experience: "6 years",
      status: "Active",
      officeAddress: "222 Cedar Street, City",
      subordinates: ["Linda", "Mike"],
      birthday: "July 30, 1988",
      contact: "+1 567-890-1234",
    },
    {
      id: 6,
      name: "Emily Davis",
      position: "Graphic Designer",
      department: "Design",
      email: "emily.davis@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "333 Oak Street, City",
      subordinates: ["Nancy", "Oscar"],
      birthday: "April 12, 1993",
      contact: "+1 678-901-2345",
    },
    {
      id: 7,
      name: "David Miller",
      position: "Financial Analyst",
      department: "Finance",
      email: "david.miller@example.com",
      experience: "7 years",
      status: "Active",
      officeAddress: "444 Elm Street, City",
      subordinates: ["Peter", "Quinn"],
      birthday: "February 25, 1982",
      contact: "+1 789-012-3456",
    },
    {
      id: 8,
      name: "Olivia Wilson",
      position: "Sales Manager",
      department: "Sales",
      email: "olivia.wilson@example.com",
      experience: "5 years",
      status: "Active",
      officeAddress: "555 Maple Street, City",
      subordinates: ["Rachel", "Steve"],
      birthday: "October 8, 1997",
      contact: "+1 890-123-4567",
    },
    {
      id: 9,
      name: "Liam Jones",
      position: "Customer Support",
      department: "Support",
      email: "liam.jones@example.com",
      experience: "2 years",
      status: "Active",
      officeAddress: "666 Pine Street, City",
      subordinates: ["Tina", "Ulysses"],
      birthday: "June 18, 1998",
      contact: "+1 901-234-5678",
    },
    {
      id: 10,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 11,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 12,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 13,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 14,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 15,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 16,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 17,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 18,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 19,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 20,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 21,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 22,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 23,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 24,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 25,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 26,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 27,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 28,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 29,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
    {
      id: 30,
      name: "Sophia Anderson",
      position: "Research Scientist",
      department: "Research",
      email: "sophia.anderson@example.com",
      experience: "4 years",
      status: "Active",
      officeAddress: "777 Cedar Street, City",
      subordinates: ["Victor", "Wendy"],
      birthday: "December 3, 1991",
      contact: "+1 987-654-3210",
    },
  ],
  data: {
    fullName: '',
    email: '',
    number: '',
    companyName: '',
    service: '',
    budget: '',
  }
};

const formSlice = createSlice({
  name: 'form',
  initialState,
  reducers: {
    setStep(state, action) {
      state.step = action.payload;
    },
    setFullName(state, action) {
      state.data.fullName = action.payload;
    },
    setEmail(state, action) {
      state.data.email = action.payload;
    },
    setNumber(state, action) {
      state.data.number = action.payload;
    },
    setCompanyName(state, action) {
      state.data.companyName = action.payload;
    },
    setService(state, action) {
      state.data.service = action.payload;
    },
    setBudget(state, action) {
      state.data.budget = action.payload;
    },
    // Add other reducer actions here using the "state" parameter
  },
});

export const { setStep, setFullName, setEmail, setNumber, setCompanyName, setService, setBudget } = formSlice.actions;
export default formSlice.reducer;
